Implement rendering app shell
rispa-io/rispa-render-server pull request #6
Opened 2017-06-23 12:02 UTC by wuzyk

2017-06-23 12:02 UTC, wuzyk commented
![](https://github.trello.services/images/mini-trello-icon.png) [33 Добавление offline режима в клиентский плагин](https://trello.com/c/xU6iJS3k/33-33-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-offline-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC%D0%B0-%D0%B2-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%81%D0%BA%D0%B8%D0%B9-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD)

2017-06-23 14:26 UTC, Laiff requested changes

2017-06-23 14:26 UTC, Laiff commented on src/render/Html.js
> +      chunk => !/bootstrap/.test(chunk)
Для нужно статического рендеринга Html был дублирован там тоже нужно внести изменения rispa-render-static/src/Html.js

2017-06-26 06:50 UTC, Laiff approved these changes

2017-06-26 06:55 UTC, merged